openapi: 3.0.0
info:
  title: Job_API
  contact: {}
  version: "1.0"
servers:
  - url: https://jobs-api.herokuapp.com/api/v1
    variables: {}
paths:
  /users/register:
    post:
      tags:
        - Auth
      summary: User Registration
      operationId: UserRegistration
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/UserRegistrationRequest"
                - example:
                    name: prashant
                    role: user
                    email: prashant10@gmail.com
                    password: "123456"
            example:
              name: prashant
              role: user
              email: prashant10@gmail.com
              password: "123456"
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /users/login:
    post:
      tags:
        - Auth
      summary: Users Login
      operationId: UsersLogin
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/UsersLoginRequest"
                - example:
                    email: test@gmail.com
                    password: "123456"
            example:
              email: test@gmail.com
              password: "123456"
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Jobs
      operationId: CreateJobs
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreateJobsRequest"
                - example:
                    company: meta
                    position: developer
            example:
              company: meta
              position: developer
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/{id}:
    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The Job ID
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/UpdateJobRequest"
                - example:
                    company: IBM
            example:
              company: IBM
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/ {id}:
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The Job ID
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    UserRegistrationRequest:
      title: UserRegistrationRequest
      required:
        - name
        - role
        - email
        - password
      type: object
      properties:
        name:
          type: string
        role:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: prashant
        role: user
        email: prashant10@gmail.com
        password: "123456"
    UsersLoginRequest:
      title: UsersLoginRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: test@gmail.com
        password: "123456"
    CreateJobsRequest:
      title: CreateJobsRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: meta
        position: developer
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - company
      type: object
      properties:
        company:
          type: string
      example:
        company: IBM
    DeleteJobRequest:
      title: DeleteJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: google
        position: intern
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Misc
    description: ""
  - name: Auth
    description: ""
  - name: Jobs
    description: ""
